=== Cobenian/rdap-conformance-tool/validator/src/main/resources/json-schema/rdap_domain.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "domain",
  "id": "rdap_domain_2.json",
  "properties": {
    "objectClassName": {
      "$ref": "rdap_domain_object.json#/definitions/domainClass"
    },
    "handle": {
      "type": "string"
    },
    "ldhName": {
      "$ref": "rdap_common.json#/definitions/ldhName"
    },
    "unicodeName": {
      "$ref": "rdap_common.json#/definitions/unicodeName"
    },
    "variants": {
      "type": "array",
      "items": {
        "$ref": "rdap_domain_object.json#/definitions/variant"
      }
    },
    "nameservers": {
      "type": "array",
      "items": {
        "$ref": "rdap_nameserver_object.json#"
      }
    },
    "secureDNS": {
      "$ref": "rdap_domain_object.json#/definitions/secureDNS"
    },
    "entities": {
      "type": "array",
      "items": {
        "$ref": "rdap_entity_object.json#"
      }
    },
    "status": {
      "$ref": "rdap_common.json#/definitions/uniqueStringArray"
    },
    "port43": {
      "$ref": "rdap_common.json#/definitions/port43"
    },
    "publicIds": {
      "$ref": "rdap_common.json#/definitions/publicIds"
    },
    "events": {
      "$ref": "rdap_common.json#/definitions/events"
    },
    "remarks": {
      "$ref": "rdap_common.json#/definitions/remarks"
    },
    "links": {
      "$ref": "rdap_common.json#/definitions/links"
    },
    "rdapConformance": {
      "$ref": "rdap_common.json#/definitions/rdapConformance"
    },
    "lang": {
      "$ref": "rdap_common.json#/definitions/lang"
    },
    "notices": {
      "$ref": "rdap_common.json#/definitions/notices"
    }
  },
  "additionalProperties": false,
  "required": [
    "objectClassName",
    "ldhName"
  ],
  "links": [
    {
      "description": "Get domain",
      "href": "/domain/{domainName}",
      "hrefSchema": {
        "properties": {
          "domainName": {
            "$ref": "rdap_common.json#/definitions/domainName"
          }
        }
      },
      "method": "GET",
      "rel": "self",
      "title": "domain",
      "targetSchema": {
        "$ref": "#"
      }
    }
  ],
  "stdRdapNoticesRemarksValidation": -12213,
  "structureInvalid": -12200,
  "stdRdapConformanceValidation": -12219,
  "unknownKeys": -12201,
  "duplicateKeys": -12202
}

=== Cobenian/rdap-conformance-tool/validator/src/test/resources/validators/domain/valid.json
{
  "objectClassName": "domain",
  "handle": "2138514_DOMAIN_COM-VRSN",
  "ldhName": "EXAMPLE.COM",
  "links": [
    {
      "value": "https://rdap.example.com/com/v1/domain/EXAMPLE.COM",
      "rel": "self",
      "href": "https://rdap.example.com/com/v1/domain/EXAMPLE.COM",
      "type": "application/rdap+json"
    },
    {
      "value": "https://rdap.markmonitor.com/rdap/domain/EXAMPLE.COM",
      "rel": "related",
      "href": "https://rdap.markmonitor.com/rdap/domain/EXAMPLE.COM",
      "type": "application/rdap+json"
    }
  ],
  "status": [
    "client delete prohibited",
    "client transfer prohibited",
    "client update prohibited",
    "server delete prohibited",
    "server transfer prohibited",
    "server update prohibited"
  ],
  "entities": [
    {
      "objectClassName": "entity",
      "handle": "292",
      "roles": [
        "registrar"
      ],
      "publicIds": [
        {
          "type": "IANA Registrar ID",
          "identifier": "292"
        }
      ],
      "vcardArray": [
        "vcard",
        [
          [
            "version",
            {},
            "text",
            "4.0"
          ],
          [
            "fn",
            {},
            "text",
            "MarkMonitor Inc."
          ]
        ]
      ],
      "entities": [
        {
          "objectClassName": "entity",
          "handle": "292",
          "roles": [
            "abuse"
          ],
          "vcardArray": [
            "vcard",
            [
              [
                "version",
                {},
                "text",
                "4.0"
              ],
              [
                "fn",
                {},
                "text",
                ""
              ],
              [
                "tel",
                {
                  "type": "voice"
                },
                "uri",
                "tel:+1.2083895740"
              ],
              [
                "email",
                {},
                "text",
                "abusecomplaints@markmonitor.com"
              ]
            ]
          ]
        }
      ]
    }
  ],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "1997-09-15T04:00:00Z"
    },
    {
      "eventAction": "expiration",
      "eventDate": "2028-09-14T04:00:00Z"
    },
    {
      "eventAction": "last update of RDAP database",
      "eventDate": "2021-03-18T09:24:18Z"
    }
  ],
  "secureDNS": {
    "delegationSigned": false
  },
  "nameservers": [
    {
      "objectClassName": "nameserver",
      "ldhName": "NS1.EXAMPLE.COM"
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS2.EXAMPLE.COM"
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS3.EXAMPLE.COM"
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS4.EXAMPLE.COM"
    }
  ],
  "rdapConformance": [
    "rdap_level_0",
    "icann_rdap_technical_implementation_guide_0",
    "icann_rdap_response_profile_0"
  ],
  "notices": [
    {
      "title": "Terms of Use",
      "description": [
        "Service subject to Terms of Use."
      ],
      "links": [
        {
          "href": "https://www.example.com/domain-names/registration-data-access-protocol/terms-service/index.xhtml",
          "type": "text/html"
        }
      ]
    },
    {
      "title": "Status Codes",
      "description": [
        "For more information on domain status codes, please visit https://icann.org/epp"
      ],
      "links": [
        {
          "href": "https://icann.org/epp",
          "type": "text/html"
        }
      ]
    },
    {
      "title": "RDDS Inaccuracy Complaint Form",
      "description": [
        "URL of the ICANN RDDS Inaccuracy Complaint Form: https://icann.org/wicf"
      ],
      "links": [
        {
          "href": "https://icann.org/wicf",
          "type": "text/html"
        }
      ]
    }
  ]
}
